### PR TITLE
Feature/homepage

### PR DESCRIPTION
**Pull request by forfeen**

### CODE REVIEW

**Comment by bameethanida** [comment]
- Should add user friendly design.

**Comment by kabilza** [comment]
Looks great and easy to see. Nice work!

**Comment by bleachjade** [comment]
The content card wasn't aligned at the center of the webpage.
You should change the CSS code to this
`.content {
  margin-left: 50px;
}`

**Comment by forfeen** [comment]
> * Should add user friendly design. @bameethanida 

already solved it

**Pull request merged**
